# Generated by Django 2.2.6 on 2020-03-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='url',
            new_name='url_1',
        ),
    ]
